* make raster.click awesome!
  + Fix undo
  + make timwriting feasable
  + alternative inplan layout
* Help myself opensource stream
  -- where I help myself by fixing opensource things
** Fix servant-client

** Cachix don't duplicate binary cache
   Currently cachix will put everything that is in the store into my repo,
   seriously limitiing the amount we can store in there.
   
   This issue is about trying to solve that: https://github.com/cachix/cachix/issues/16
   
   I think the CLI argument is an easy solution to this, eg:
    `cachix push mycache --exclude-present-in https://cache.nixos.org`


* FONT STREAM!!!

* Fix emacs stream
* The great nix stream
  write about nix things?
* ADTs presentation prep stream

* Rust stream
** Make game run
** Implement functor, applicative, monad, traversable, foldable, profunctor
   Maybe with help of parser combinator course for first three?
   Profunctor for let's lens?

* Language review
  Look at obscure langauges and built something non-trivial?
  
** Mecury
** ATS
http://www.ats-lang.org/


* Halogen & purescript

** For nix bois:
https://github.com/justinwoo/easy-purescript-nix 

** Examples
https://github.com/thomashoneyman/purescript-halogen-realworld 

** Hoogle
https://pursuit.purescript.org 


** PSCID
https://github.com/kRITZCREEK/pscid 
* Racket
  If I want to become a lisp boi
