* Toy problems
https://benchmarksgame-team.pages.debian.net/benchmarksgame/performance/nbody.html

* make raster.click awesome!
  + Fix undo
  + make timwriting feasable
  + alternative inplan layout
* Help myself opensource stream
  -- where I help myself by fixing opensource things
** Fix servant-client

** Add Char to datakind in GHC
** Cachix don't duplicate binary cache
   Currently cachix will put everything that is in the store into my repo,
   seriously limitiing the amount we can store in there.
   
   This issue is about trying to solve that: https://github.com/cachix/cachix/issues/16
   
   I think the CLI argument is an easy solution to this, eg:
    `cachix push mycache --exclude-present-in https://cache.nixos.org`


* FONT STREAM!!!

* Fix emacs stream
* The great nix stream
  write about nix things?
* ADTs presentation prep stream

* Rust stream
** Make game run
** Implement functor, applicative, monad, traversable, foldable, profunctor
   Maybe with help of parser combinator course for first three?
   Profunctor for let's lens?

* Language review
  Look at obscure langauges and built something non-trivial?
  


** Clojure
   
*** DONE Implemented a rock paper siccors bot
https://github.com/jappeace/rock-paper-siccors

*** TODO I wan't to make a game w/ clojurescript
    Lumie had the suggestion of using conduit for example: https://jacekschae.github.io/conduit-re-frame-10x-demo/


** Idris
   N body?
   
** Coq
   Proof to the world I can proof
   Proof the existence of pi
   Eat pi
   
   jap-pi

** Shen lisp
   Make linear types of course

** Mecury
** ATS
http://www.ats-lang.org/

** APL 
   Array based langague.

   It has the annoying symbols.

https://en.wikipedia.org/wiki/APL_(programming_language)

https://github.com/lokedhs/gnu-apl-mode

Consider using oneko for additional frustrations

** Hackett
   Countoren sugessted using hackett.
   A strongly typed lisp trying to create typefull macros

https://github.com/lexi-lambda/hackett

https://lexi-lambda.github.io/hackett/
* Halogen & purescript

** For nix bois:
https://github.com/justinwoo/easy-purescript-nix 

** Examples
https://github.com/thomashoneyman/purescript-halogen-realworld 

** Hoogle
https://pursuit.purescript.org 


** PSCID
https://github.com/kRITZCREEK/pscid 
* Racket
  If I want to become a lisp boi


* Hacking editors
- read a morning paper
- setup epic font in atom, make as extension
- twitch extension for vscode
