* Toy problems
https://benchmarksgame-team.pages.debian.net/benchmarksgame/performance/nbody.html

* make raster.click awesome!
  + Fix undo
  + make timwriting feasable
  + alternative inplan layout
* Help myself opensource stream
  -- where I help myself by fixing opensource things
** Fix servant-client

** Fix compton workspace switching
   At the moment the fade effect when switching workspace
   is just slow

* Fix emacs stream
* The great nix stream
  write about nix things?
* ADTs presentation prep stream

* Rust stream
** Make game run
** Implement functor, applicative, monad, traversable, foldable, profunctor
   Maybe with help of parser combinator course for first three?
   Profunctor for let's lens?

* Language review
  Look at obscure langauges and built something non-trivial?
  


** Idris
   N body?
   
** Coq
   Proof to the world I can proof
   Proof the existence of pi
   Eat pi
   
   jap-pi

** Shen lisp
   Make linear types of course

** Mecury
** ATS
http://www.ats-lang.org/

** APL 
   Array based langague.

   It has the annoying symbols.

https://en.wikipedia.org/wiki/APL_(programming_language)

https://github.com/lokedhs/gnu-apl-mode

* Halogen & purescript

** For nix bois:
https://github.com/justinwoo/easy-purescript-nix 

** Examples
https://github.com/thomashoneyman/purescript-halogen-realworld 

** Hoogle
https://pursuit.purescript.org 


** PSCID
https://github.com/kRITZCREEK/pscid 
* Racket
  If I want to become a lisp boi
